// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaX2IIX4YGA9diDdDXRADWsWLvvOfEiVE',
    appId: '1:83383668807:web:1ff21a5b2d6884b57aa162',
    messagingSenderId: '83383668807',
    projectId: 'carrito-patita',
    authDomain: 'carrito-patita.firebaseapp.com',
    storageBucket: 'carrito-patita.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8rUlomvzg3KIjB8vI6v81rK5ougMyyww',
    appId: '1:83383668807:android:bce0f4ce954f115a7aa162',
    messagingSenderId: '83383668807',
    projectId: 'carrito-patita',
    storageBucket: 'carrito-patita.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBExlo_qwLc5mR7EBnUOI_dlizgJNBSlWA',
    appId: '1:83383668807:ios:6a58a29d37de45557aa162',
    messagingSenderId: '83383668807',
    projectId: 'carrito-patita',
    storageBucket: 'carrito-patita.appspot.com',
    iosClientId: '83383668807-r2q0st6kgg6f1mrlq44imftd2knui48v.apps.googleusercontent.com',
    iosBundleId: 'com.example.carritoPaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBExlo_qwLc5mR7EBnUOI_dlizgJNBSlWA',
    appId: '1:83383668807:ios:6a58a29d37de45557aa162',
    messagingSenderId: '83383668807',
    projectId: 'carrito-patita',
    storageBucket: 'carrito-patita.appspot.com',
    iosClientId: '83383668807-r2q0st6kgg6f1mrlq44imftd2knui48v.apps.googleusercontent.com',
    iosBundleId: 'com.example.carritoPaty',
  );
}
